# Netlify Configuration for React Frontend

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
